name: libreoffice
version: 6.2.0.3
summary: LibreOffice is a free and open source office suite
description: LibreOffice is a free and open source office suite, developed by The Document Foundation. The LibreOffice suite comprises programs for word processing, the creation and editing of spreadsheets, slideshows, diagrams and drawings, working with databases, and composing mathematical formulae.
confinement: strict
base: core18

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

parts:
    # Launchpad builders have a timeout for how long they are allowed to access
    # the internet (through a proxy) starting from the start of the build.
    # Since the libreoffice part takes a long time to build, we need to ensure
    # that it is the last one to build, so that all other parts have had a
    # chance to pull their build and stage packages before the proxy
    # authentication is revoked.

    libreoffice-patches:
        plugin: dump
        source: patches
        organize:
            '*' : patches/
        override-prime: ""

    libreoffice:
        after:
            - libreoffice-patches
            - libreoffice-wrapper
            - spellchecking
            - hyphenation
            - thesauri
            - jvm
            - gstreamer
            - gtk3-locales
            - desktop-settings-packages
        plugin: autotools
        source: https://dev-builds.libreoffice.org/pre-releases/src/libreoffice-6.2.0.3.tar.xz
        build-attributes: [ no-system-libraries ]
        configflags:
            - --disable-ccache
            - --disable-coinmp
            - --disable-dconf
            - --disable-evolution2
            - --disable-firebird-sdbc
            - --disable-gstreamer-0-10
            - --disable-kde4
            - --disable-online-update
            - --enable-dbus
            - --enable-eot
            - --enable-ext-mariadb-connector
            - --enable-ext-wiki-publisher
            - --enable-extension-integration
            - --enable-gstreamer-1-0
            - --enable-mergelibs
            - --enable-release-build
            - --enable-scripting-beanshell
            - --enable-scripting-javascript
            - --with-alloc=system
            - --with-build-version=libreoffice-6.2.0.3-snap1
            - --with-gdrive-client-id=424119844901.apps.googleusercontent.com
            - --with-gdrive-client-secret=AIienwDlGIIsHoKnNHmWGXyJ
            - --with-system-graphite
            - --with-system-harfbuzz
            - --with-system-icu
            - --with-system-libexttextcat
            - --with-system-openldap
            - --with-system-nss
            - --with-system-hsqldb
            - --with-hsqldb-jar=/usr/share/java/hsqldb1.8.0.jar
            - --with-theme=colibre tango sifr breeze elementary
            - --with-vendor=Canonical, Ltd.
            - --disable-postgresql-sdbc
            - --with-help
            - --without-doxygen
            - --with-lang=en-US de es fr it pt pt-BR ja zh-TW ru ca
        build-packages:
            - quilt
            - ant
            - ant-optional
            - bison
            - build-essential
            - default-jdk
            - doxygen
            - flex
            - gdb
            - gettext
            - gperf
            - junit4
            - kdelibs5-dev
            - libarchive-zip-perl
            - libatk1.0-dev
            - libbluetooth-dev
            - libcairo2-dev
            - libcups2-dev
            - libcurl4-gnutls-dev
            - libdbus-glib-1-dev
            - libe-book-dev
            - libeot-dev
            - libexpat1-dev
            - libexttextcat-dev
            - libfontconfig1-dev
            - libfreehand-dev
            - libfreetype6-dev
            - libgconf2-dev
            - libgirepository1.0-dev
            - libgl1-mesa-glx
            - libglew-dev
            - libglib2.0-dev
            - libglm-dev
            - libgraphite2-dev
            - libgstreamer-plugins-base1.0-dev
            - libgstreamer1.0-dev
            - libgtk-3-dev
            - libgtk2.0-dev
            - libharfbuzz-dev
            - libhsqldb1.8.0-java
            - libhunspell-dev
            - libhyphen-dev
            - libice-dev
            - libicu-dev
            - libjpeg-dev
            - liblangtag-dev
            - liblcms2-dev
            - libldap2-dev
            - libmysqlclient-dev
            - libmysqlcppconn-dev
            - libmythes-dev
            - libnspr4-dev
            - libnss3-dev
            - libpng-dev
            - libpoppler-cpp-dev
            - libpoppler-dev
            - libpoppler-private-dev
            - libpq-dev
            - libpython3-dev
            - libqt4-dev
            - librdf0-dev
            - libsane-dev
            - libsm-dev
            - libssl-dev
            - libsuitesparse-dev
            - libvisio-dev
            - libx11-dev
            - libxaw7-dev
            - libxext-dev
            - libxinerama-dev
            - libxkbfile-dev
            - libxml2
            - libxml2-dev
            - libxml2-utils
            - libxrandr-dev
            - libxrender-dev
            - libxslt1-dev
            - libxslt1.1
            - libxt-dev
            - libxtst-dev
            - locales-all
            - maven-repo-helper
            - python3-dev
            - unixodbc-dev
            - unzip
            - wget
            - x11proto-render-dev
            - xorg
            - xsltproc
            - zip
            - zlib1g-dev
        stage-packages:
            - libatk1.0-0
            - libcairo2
            - libdbus-glib-1-2
            - libexttextcat-2.0-0
            - libfreetype6
            - libgconf-2-4
            - libgl1-mesa-glx
            - libglib2.0-0
            - libgtk-3-bin
            - libgtk2.0-0
            - libharfbuzz-icu0
            - libhsqldb1.8.0-java
            - libldap-2.4-2
            - libnspr4
            - libnss3
            - libpython3.6
            - libsm6
            - libxml2
            - libxslt1.1
            - libx11-6
            - libxext6
            - libxinerama1
            - libxrandr2
            - libxrender1
        override-build: |
            set -eux
            QUILT_PATCHES=$SNAPCRAFT_STAGE/patches quilt push -a
            export LANG=en_US.UTF-8
            export LC_ALL=en_US.UTF-8
            snapcraftctl build
            srcdir=$PWD
            cd workdir/CustomTarget/sysui/share/libreoffice
            SRCDIR=$srcdir INSTDIR=$srcdir/instdir DESTDIR=$SNAPCRAFT_PART_INSTALL PREFIXDIR=usr GNOMEDIR=usr PKG_CONFIG=pkg-config ./create_tree.sh
            chmod a+x $SNAPCRAFT_PART_INSTALL/usr/share
            for app in base calc draw impress math startcenter writer
            do
                sed -i \
                    -e "s#Icon=libreoffice6.2-$app#Icon=/usr/share/icons/gnome/256x256/apps/libreoffice6.2-$app.png#" \
                    -e "s#^Exec=libreoffice6.2 --\(.*\)#Exec=libreoffice.\1#g" \
                    $SNAPCRAFT_PART_INSTALL/lib/libreoffice/share/xdg/$app.desktop
            done
        prime:
            - lib/libreoffice/*
            - -lib/libreoffice/share/fonts
            - usr/lib/*/lib*
            - usr/lib/*/mesa/lib*
            - usr/share/icons/gnome/256x256/apps/*
            - usr/share/java/
            - usr/sbin/*

    libreoffice-wrapper:
        plugin: dump
        source: .
        prime:
            - libreoffice.wrapper
            - javasettings.py
            - filebug.py
            - data-dir/*
        after: [desktop-gtk3]

    desktop-gtk3:
        # Exclude unity-gtk-module from the upstream part as it causes a crash
        # when starting libreoffice.math on Ubuntu 16.04
        # (https://launchpad.net/bugs/1755178), and it's not needed anyway
        # because libreoffice talks GMenuModel already.
        stage:
            - -usr/lib/*/gtk-3.0/modules/libunity-gtk-module.so

    spellchecking:
        plugin: nil
        stage-packages:
            - hunspell-de-de
            - hunspell-en-au
            - hunspell-en-ca
            - hunspell-en-gb
            - hunspell-en-us
            - hunspell-en-za
            - hunspell-fr-classical
            - hunspell-it
            - hunspell-pl
            - myspell-es
            - myspell-pt-br
            - myspell-pt-pt

    hyphenation:
        plugin: nil
        stage-packages:
            - hyphen-de
            - hyphen-en-gb
            - hyphen-en-us
            - hyphen-es
            - hyphen-fr
            - hyphen-it
            - hyphen-pt-br
            - hyphen-pt-pt

    thesauri:
        plugin: nil
        stage-packages:
            - mythes-en-au
            - mythes-en-us
            - mythes-fr

    jvm:
        plugin: nil
        build-attributes: [ no-system-libraries ]
        stage-packages:
            - openjdk-11-jre
        prime:
            - -usr/share/doc

    gstreamer:
        # GStreamer packages needed for audio/video clip playback in office
        # documents. Libreoffice uses the gtksink element, which in Ubuntu
        # 16.04 is part of gstreamer1.0-plugins-bad. As of Ubuntu 18.04 it has
        # made its way to gstreamer1.0-plugins-good, so when the snap is built
        # on 18.04 that list of stage packages will need updating.
        # Ref: https://launchpad.net/bugs/1752166.
        plugin: nil
        build-attributes: [ no-system-libraries ]
        stage-packages:
            - gstreamer1.0-libav
            - gstreamer1.0-plugins-bad
            - gstreamer1.0-plugins-base
            - gstreamer1.0-plugins-good
            - gstreamer1.0-pulseaudio
            - libaa1
            - libass9
            - libavcodec57
            - libavfilter6
            - libavformat57
            - libavresample3
            - libavutil55
            - libbluray2
            - libbs2b0
            - libbz2-1.0
            - libcairo-gobject2
            - libcrystalhd3
            - libcurl3-gnutls
            - libde265-0
            - libdv4
            - libfaad2
            - libffi6
            - libflac8
            - libflite1
            - libfribidi0
            - libglu1-mesa
            - libgme0
            - libgmp10
            - libgnutls30
            - libgomp1
            - libgpm2
            - libgsm1
            - libgstreamer-plugins-bad1.0-0
            - libgstreamer-plugins-base1.0-0
            - libgstreamer-plugins-good1.0-0
            - libgstreamer1.0-0
            - libhogweed4
            - libidn2-0
            - libmp3lame0
            - libmodplug1
            - libnettle6
            - libnuma1
            - libogg0
            - libopenal1
            - libopenal-data
            - libopencv-core3.2
            - libopencv-imgproc3.2
            - libopenjp2-7
            - libopus0
            - liborc-0.4-0
            - libp11-kit0
            - libpostproc54
            - librtmp1
            - libshine3
            - libslang2
            - libsnappy1v5
            - libsodium23
            - libsoup2.4-1
            - libsoxr0
            - libspeex1
            - libssh-gcrypt-4
            - libswresample2
            - libswscale4
            - libtasn1-6
            - libtbb2
            - libtheora0
            - libtwolame0
            - libunistring2
            - libv4l-0
            - libva2
            - libvorbis0a
            - libvpx5
            - libwavpack1
            - libwebp6
            - libx264-152
            - libx265-146
            - libxvidcore4
            - libzmq5
            - libzvbi0
            - zlib1g

    # In Ubuntu compiled locales for GTK are installed by langpacks, not by
    # libgtk-3-common. Fetch all the langpacks and keep only the GTK locales.
    gtk3-locales:
        plugin: nil
        build-packages:
            - apt
            - dpkg
        override-pull: |
            set -eux
            apt download "language-pack-gnome-*-base"
        override-build: |
            set -eux
            for deb in *.deb; do dpkg-deb -x $deb .; done
            find usr/share/locale-langpack -type f -not -name "gtk30*.mo" -exec rm '{}' \;
            mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share
            cp -R usr/share/locale-langpack $SNAPCRAFT_PART_INSTALL/usr/share/

    # Ship a default set of GSettings schemas so that the correct theme is used
    # in Wayland sessions on Ubuntu (see https://forum.snapcraft.io/t/7806/3).
    desktop-settings-packages:
        plugin: nil
        build-packages:
            - libglib2.0-bin
        stage-packages:
            - gsettings-desktop-schemas
            - ubuntu-settings
        prime:
            - usr/share/glib-2.0/schemas/*
    desktop-settings-build:
        plugin: nil
        after: [ desktop-settings-packages, libreoffice ]
        override-prime: |
            set -eux
            glib-compile-schemas usr/share/glib-2.0/schemas

apps:
    libreoffice:
        command: libreoffice.wrapper
        desktop: lib/libreoffice/share/xdg/startcenter.desktop
        environment: &environment
            TMPDIR: $XDG_RUNTIME_DIR
        plugs: &plugs
            - bluez
            - cups-control
            - desktop
            - gsettings
            - home
            - network
            - network-bind
            - opengl
            - pulseaudio
            - removable-media
            - screen-inhibit-control
            - unity7
            - wayland
    base:
        command: libreoffice.wrapper --base
        desktop: lib/libreoffice/share/xdg/base.desktop
        environment: *environment
        plugs: *plugs
    calc:
        command: libreoffice.wrapper --calc
        desktop: lib/libreoffice/share/xdg/calc.desktop
        environment: *environment
        plugs: *plugs
    draw:
        command: libreoffice.wrapper --draw
        desktop: lib/libreoffice/share/xdg/draw.desktop
        environment: *environment
        plugs: *plugs
    impress:
        command: libreoffice.wrapper --impress
        desktop: lib/libreoffice/share/xdg/impress.desktop
        environment: *environment
        plugs: *plugs
    math:
        command: libreoffice.wrapper --math
        desktop: lib/libreoffice/share/xdg/math.desktop
        environment: *environment
        plugs: *plugs
    writer:
        command: libreoffice.wrapper --writer
        desktop: lib/libreoffice/share/xdg/writer.desktop
        environment: *environment
        plugs: *plugs
    filebug:
        command: filebug.py
        environment: *environment
        plugs:
            - desktop
            - network
