name: libreoffice
version: 5.0.4
# The vendor for the snap (replace 'Vendor <email@example.com>')
#vendor: Canonical <info@canonical.com>
summary: LibreOffice is a free and open source office suite
description: LibreOffice is a free and open source office suite, developed by The Document Foundation. The LibreOffice suite comprises programs for word processing, the creation and editing of spreadsheets, slideshows, diagrams and drawings, working with databases, and composing mathematical formulae.
icon: libreoffice.png
parts:
    libreoffice-build:
        plugin: make
        source: ./libreoffice-build/
#        build-packages:
        stage-packages:
            - libatk1.0-0
            - libcairo2
            - libdbus-glib-1-2
            - libfreetype6
            - libgconf-2-4
            - libgl1-mesa-glx
            - libglib2.0-0
            - libgstreamer-plugins-base1.0-0
            - libgstreamer1.0-0
            - libgtk2.0-0
            - libnspr4
            - libnss3
            - libxml2
            - libxslt1.1
            - libatk1.0-dev
            - libcairo2-dev
            - libdbus-glib-1-dev
            - libfreetype6-dev
            - libgconf2-dev
            - libglib2.0-dev
            - libgstreamer-plugins-base1.0-dev
            - libgstreamer1.0-dev
            - libgtk2.0-dev
            - libnspr4-dev
            - libnss3-dev
            - libpython3.5-dev
            - libxml2-dev
            - python3-dev
            - gdb
            - strace
            - xmir
            - xorg
        snap:
            - usr/local/*
            - usr/bin/gdb
            - usr/bin/strace
            - usr/lib/x86_64-linux-gnu/lib*
            - usr/lib/x86_64-linux-gnu/mesa/lib*
