name: libreoffice
version: 5.4.1.2
summary: LibreOffice is a free and open source office suite
description: LibreOffice is a free and open source office suite, developed by The Document Foundation. The LibreOffice suite comprises programs for word processing, the creation and editing of spreadsheets, slideshows, diagrams and drawings, working with databases, and composing mathematical formulae.
confinement: strict

parts:
    libreoffice:
        plugin: autotools
        source: http://ftp.utexas.edu/libreoffice/libreoffice/src/5.4.1/libreoffice-5.4.1.2.tar.xz
        configflags:
            - --disable-ccache
            - --disable-coinmp
            - --disable-dconf
            - --disable-evolution2
            - --disable-firebird-sdbc
            - --disable-gltf
            - --disable-gstreamer-0-10
            - --disable-kde4
            - --disable-online-update
            - --enable-dbus
            - --enable-eot
            - --enable-ext-mariadb-connector
            - --enable-ext-wiki-publisher
            - --enable-extension-integration
            - --enable-gstreamer-1-0
            - --enable-mergelibs
            - --enable-release-build
            - --enable-scripting-beanshell
            - --enable-scripting-javascript
            - --with-alloc=system
            - --with-build-version=libreoffice-5.4.1.2-snap1
            - --with-gdrive-client-id=424119844901.apps.googleusercontent.com
            - --with-gdrive-client-secret=AIienwDlGIIsHoKnNHmWGXyJ
            - --with-system-libexttextcat
            - --with-system-openldap
            - --with-system-nss
            - --with-system-hsqldb
            - --with-hsqldb-jar=/usr/share/java/hsqldb1.8.0.jar
            - --with-theme=galaxy hicontrast oxygen tango sifr breeze elementary
            - --with-vendor=Canonical, Ltd.
            - --disable-postgresql-sdbc
            - --with-help
            - --without-doxygen
            - --with-lang=en-US de es fr it pt pt-BR
        build-packages:
            - ant
            - ant-optional
            - bison
            - build-essential
            - default-jdk
            - doxygen
            - flex
            - gdb
            - gettext
            - gperf
            - graphviz
            - junit4
            - kdelibs5-dev
            - libarchive-zip-perl
            - libatk1.0-dev
            - libbluetooth-dev
            - libcairo2-dev
            - libcups2-dev
            - libcurl4-gnutls-dev
            - libdbus-glib-1-dev
            - libe-book-dev
            - libeot-dev
            - libexpat1-dev
            - libexttextcat-dev
            - libfontconfig1-dev
            - libfreehand-dev
            - libfreetype6-dev
            - libgconf2-dev
            - libgirepository1.0-dev
            - libgl1-mesa-glx
            - libglew-dev
            - libglib2.0-dev
            - libglm-dev
            - libgraphite2-dev
            - libgstreamer-plugins-base1.0-dev
            - libgstreamer1.0-dev
            - libgtk-3-dev
            - libgtk2.0-dev
            - libharfbuzz-dev
            - libhsqldb1.8.0-java
            - libhunspell-dev
            - libhyphen-dev
            - libice-dev
            - libicu-dev
            - libjpeg-dev
            - libkrb5-dev
            - liblangtag-dev
            - liblcms2-dev
            - libldap2-dev
            - libmysqlclient-dev
            - libmysqlcppconn-dev
            - libmythes-dev
            - libnspr4-dev
            - libnss3-dev
            - liborcus-dev
            - libpng12-dev
            - libpoppler-cpp-dev
            - libpoppler-dev
            - libpoppler-private-dev
            - libpq-dev
            - libpython3.5-dev
            - libqt4-dev
            - librdf0-dev
            - libsane-dev
            - libsm-dev
            - libssl-dev
            - libsuitesparse-dev
            - libvigraimpex-dev
            - libvisio-dev
            - libx11-dev
            - libxaw7-dev
            - libxext-dev
            - libxinerama-dev
            - libxkbfile-dev
            - libxml2
            - libxml2-dev
            - libxml2-utils
            - libxrandr-dev
            - libxrender-dev
            - libxslt1-dev
            - libxslt1.1
            - libxt-dev
            - libxtst-dev
            - maven-repo-helper
            - patch
            - python3-dev
            - unixodbc-dev
            - unzip
            - wget
            - x11proto-render-dev
            - xorg
            - xsltproc
            - zip
            - zlib1g-dev
        stage-packages:
            - default-jdk
            - graphviz
            - libatk1.0-0
            - libatk1.0-dev
            - libcairo2
            - libcairo2-dev
            - libdbus-glib-1-2
            - libdbus-glib-1-dev
            - libexttextcat-dev
            - libfreetype6
            - libfreetype6-dev
            - libgconf-2-4
            - libgconf2-dev
            - libgl1-mesa-glx
            - libglib2.0-0
            - libglib2.0-dev
            - libgstreamer-plugins-base1.0-0
            - libgstreamer-plugins-base1.0-dev
            - libgstreamer1.0-0
            - libgstreamer1.0-dev
            - libgtk-3-bin
            - libgtk-3-dev
            - libgtk2.0-0
            - libgtk2.0-dev
            - libhsqldb1.8.0-java
            - libkrb5-dev
            - libldap2-dev
            - libnspr4
            - libnspr4-dev
            - libnss3
            - libnss3-dev
            - liborcus-dev
            - libpython3.5-dev
            - libxml2
            - libxml2-dev
            - libxslt1.1
            - python3-dev
            - xorg
        prepare: |
            for patch in $(cat ../../../snap/patches/series)
            do
                patch -d . -p1 < ../../../snap/patches/$patch
            done
        install: |
            cd workdir/CustomTarget/sysui/share/libreoffice
            DESTDIR=$SNAPCRAFT_PART_INSTALL PREFIXDIR=usr GNOMEDIR=usr ./create_tree.sh
            chmod a+x $SNAPCRAFT_PART_INSTALL/usr/share
            for app in base calc draw impress math startcenter writer
            do
                sed -i "s#Icon=libreoffice5.4-$app#Icon=/usr/share/icons/gnome/256x256/apps/libreoffice5.4-$app.png#" $SNAPCRAFT_PART_INSTALL/lib/libreoffice/share/xdg/$app.desktop
            done
        prime:
            - lib/libreoffice/*
            - usr/lib/*/lib*
            - usr/lib/*/mesa/lib*
            - usr/sbin/*
            - usr/share/icons/gnome*

    libreoffice-wrapper:
        plugin: dump
        source: .
        prime:
            - libreoffice.wrapper
            - no-wayland-hack
        after: [desktop-gtk3]

    selected-fonts:
        plugin: nil
        stage-packages:
            - fonts-sil-gentium
            - fonts-sil-gentium-basic
            - fonts-liberation
            - ttf-dejavu-core
            - ttf-ubuntu-font-family

    jvm:
        plugin: nil
        stage-packages:
            - openjdk-8-jdk
            - openjdk-8-jre

apps:
    libreoffice:
        command: libreoffice.wrapper
        desktop: lib/libreoffice/share/xdg/startcenter.desktop
        plugs: &plugs
            - bluez
            - cups-control
            - home
            - network
            - network-bind
            - opengl
            - unity7
    base:
        command: libreoffice.wrapper --base
        desktop: lib/libreoffice/share/xdg/base.desktop
        plugs: *plugs
    calc:
        command: libreoffice.wrapper --calc
        desktop: lib/libreoffice/share/xdg/calc.desktop
        plugs: *plugs
    draw:
        command: libreoffice.wrapper --draw
        desktop: lib/libreoffice/share/xdg/draw.desktop
        plugs: *plugs
    impress:
        command: libreoffice.wrapper --impress
        desktop: lib/libreoffice/share/xdg/impress.desktop
        plugs: *plugs
    math:
        command: libreoffice.wrapper --math
        desktop: lib/libreoffice/share/xdg/math.desktop
        plugs: *plugs
    writer:
        command: libreoffice.wrapper --writer
        desktop: lib/libreoffice/share/xdg/writer.desktop
        plugs: *plugs
