name: libreoffice
version: 6.0.1.1
summary: LibreOffice is a free and open source office suite
description: LibreOffice is a free and open source office suite, developed by The Document Foundation. The LibreOffice suite comprises programs for word processing, the creation and editing of spreadsheets, slideshows, diagrams and drawings, working with databases, and composing mathematical formulae.
confinement: strict

parts:
    # Launchpad builders have a timeout for how long they are allowed to access
    # the internet (through a proxy) starting from the start of the build.
    # Since the libreoffice part takes a long time to build, we need to ensure
    # that it is the last one to build, so that all other parts have had a
    # chance to pull their build and stage packages before the proxy
    # authentication is revoked.
    # Since the generation of the caches needs to run after the libreoffice
    # part, it is artificially split into two parts: one that installs the build
    # and stage packages before the libreoffice part is built, and one that does
    # the actual generation of the caches after the libreoffice part is built.

    libreoffice:
        after:
            - libreoffice-wrapper
            - themes
            - spellchecking
            - hyphenation
            - thesauri
            - jvm
            - caches-packages
        plugin: autotools
        source: https://download.documentfoundation.org/libreoffice/src/6.0.1/libreoffice-6.0.1.1.tar.xz
        configflags:
            - --disable-ccache
            - --disable-coinmp
            - --disable-dconf
            - --disable-evolution2
            - --disable-firebird-sdbc
            - --disable-gltf
            - --disable-gstreamer-0-10
            - --disable-kde4
            - --disable-online-update
            - --enable-dbus
            - --enable-eot
            - --enable-ext-mariadb-connector
            - --enable-ext-wiki-publisher
            - --enable-extension-integration
            - --enable-gstreamer-1-0
            - --enable-mergelibs
            - --enable-release-build
            - --enable-scripting-beanshell
            - --enable-scripting-javascript
            - --with-alloc=system
            - --with-build-version=libreoffice-6.0.1.1-snap1
            - --with-gdrive-client-id=424119844901.apps.googleusercontent.com
            - --with-gdrive-client-secret=AIienwDlGIIsHoKnNHmWGXyJ
            - --with-system-graphite
            - --with-system-harfbuzz
            - --with-system-icu
            - --with-system-libexttextcat
            - --with-system-openldap
            - --with-system-nss
            - --with-system-hsqldb
            - --with-hsqldb-jar=/usr/share/java/hsqldb1.8.0.jar
            - --with-theme=galaxy hicontrast oxygen tango sifr breeze elementary
            - --with-vendor=Canonical, Ltd.
            - --disable-postgresql-sdbc
            - --with-help
            - --without-doxygen
            - --with-lang=en-US de es fr it pt pt-BR ja zh-TW ru
        build-packages:
            - ant
            - ant-optional
            - bison
            - build-essential
            - default-jdk
            - doxygen
            - flex
            - gdb
            - gettext
            - gperf
            - graphviz
            - junit4
            - kdelibs5-dev
            - libarchive-zip-perl
            - libatk1.0-dev
            - libbluetooth-dev
            - libcairo2-dev
            - libcups2-dev
            - libcurl4-gnutls-dev
            - libdbus-glib-1-dev
            - libe-book-dev
            - libeot-dev
            - libexpat1-dev
            - libexttextcat-dev
            - libfontconfig1-dev
            - libfreehand-dev
            - libfreetype6-dev
            - libgconf2-dev
            - libgirepository1.0-dev
            - libgl1-mesa-glx
            - libglew-dev
            - libglib2.0-dev
            - libglm-dev
            - libgraphite2-dev
            - libgstreamer-plugins-base1.0-dev
            - libgstreamer1.0-dev
            - libgtk-3-dev
            - libgtk2.0-dev
            - libharfbuzz-dev
            - libhsqldb1.8.0-java
            - libhunspell-dev
            - libhyphen-dev
            - libice-dev
            - libicu-dev
            - libjpeg-dev
            - libkrb5-dev
            - liblangtag-dev
            - liblcms2-dev
            - libldap2-dev
            - libmysqlclient-dev
            - libmysqlcppconn-dev
            - libmythes-dev
            - libnspr4-dev
            - libnss3-dev
            - liborcus-dev
            - libpng-dev
            - libpoppler-cpp-dev
            - libpoppler-dev
            - libpoppler-private-dev
            - libpq-dev
            - libpython3.5-dev
            - libqt4-dev
            - librdf0-dev
            - libsane-dev
            - libsm-dev
            - libssl-dev
            - libsuitesparse-dev
            - libvisio-dev
            - libx11-dev
            - libxaw7-dev
            - libxext-dev
            - libxinerama-dev
            - libxkbfile-dev
            - libxml2
            - libxml2-dev
            - libxml2-utils
            - libxrandr-dev
            - libxrender-dev
            - libxslt1-dev
            - libxslt1.1
            - libxt-dev
            - libxtst-dev
            - maven-repo-helper
            - patch
            - python3-dev
            - unixodbc-dev
            - unzip
            - wget
            - x11proto-render-dev
            - xorg
            - xsltproc
            - zip
            - zlib1g-dev
        stage-packages:
            - default-jdk
            - graphviz
            - libatk1.0-0
            - libatk1.0-dev
            - libcairo2
            - libcairo2-dev
            - libdbus-glib-1-2
            - libdbus-glib-1-dev
            - libexttextcat-dev
            - libfreetype6
            - libfreetype6-dev
            - libgconf-2-4
            - libgconf2-dev
            - libgl1-mesa-glx
            - libglib2.0-0
            - libglib2.0-dev
            - libgstreamer-plugins-base1.0-0
            - libgstreamer-plugins-base1.0-dev
            - libgstreamer1.0-0
            - libgstreamer1.0-dev
            - libgtk-3-bin
            - libgtk-3-dev
            - libgtk2.0-0
            - libgtk2.0-dev
            - libhsqldb1.8.0-java
            - libkrb5-dev
            - libldap2-dev
            - libnspr4
            - libnspr4-dev
            - libnss3
            - libnss3-dev
            - liborcus-dev
            - libpython3.5-dev
            - libxml2
            - libxml2-dev
            - libxslt1.1
            - python3-dev
            - xorg
        prepare: |
            set -eux
            for patch in $(cat ../../../snap/patches/series)
            do
                patch -d . -p1 < ../../../snap/patches/$patch
            done
        install: |
            set -eux
            srcdir=$PWD
            cd workdir/CustomTarget/sysui/share/libreoffice
            SRCDIR=$srcdir INSTDIR=$srcdir/instdir DESTDIR=$SNAPCRAFT_PART_INSTALL PREFIXDIR=usr GNOMEDIR=usr PKG_CONFIG=pkg-config ./create_tree.sh
            chmod a+x $SNAPCRAFT_PART_INSTALL/usr/share
            for app in base calc draw impress math startcenter writer
            do
                sed -i \
                    -e "s#Icon=libreoffice6.0-$app#Icon=/usr/share/icons/gnome/256x256/apps/libreoffice6.0-$app.png#" \
                    -e "s#^Exec=libreoffice6.0 --\(.*\)#Exec=libreoffice.\1#g" \
                    $SNAPCRAFT_PART_INSTALL/lib/libreoffice/share/xdg/$app.desktop
            done
        prime:
            - lib/libreoffice/*
            - -lib/libreoffice/share/fonts
            - usr/lib/*/lib*
            - usr/lib/*/mesa/lib*
            - usr/share/java/
            - usr/sbin/*

    libreoffice-wrapper:
        plugin: dump
        source: .
        prime:
            - libreoffice.wrapper
        after: [desktop-gtk3]

    themes:
        plugin: nil
        stage-packages:
            - light-themes
            - ubuntu-settings

    spellchecking:
        plugin: nil
        stage-packages:
            - hunspell-de-de
            - hunspell-en-au
            - hunspell-en-ca
            - hunspell-en-gb
            - hunspell-en-us
            - hunspell-en-za
            - hunspell-fr-classical
            - hunspell-it
            - hunspell-pl
            - myspell-es
            - myspell-pt-br
            - myspell-pt-pt

    hyphenation:
        plugin: nil
        stage-packages:
            - hyphen-de
            - hyphen-en-gb
            - hyphen-en-us
            - hyphen-es
            - hyphen-fr
            - hyphen-it
            - hyphen-pt-br
            - hyphen-pt-pt

    thesauri:
        plugin: nil
        stage-packages:
            - mythes-en-au
            - mythes-en-us
            - mythes-fr

    jvm:
        plugin: nil
        stage-packages:
            - openjdk-8-jdk
            - openjdk-8-jre

    caches-packages:
        plugin: nil
        stage-packages:
            - adwaita-icon-theme
            - gnome-icon-theme
            - gsettings-desktop-schemas
            - hicolor-icon-theme
            - humanity-icon-theme
            - libgtk-3-common
            - shared-mime-info
            - ubuntu-mono
            - ubuntu-settings
            - unity-gtk-module-common
        build-packages:
            - gtk-update-icon-cache
            - libglib2.0-bin
            - shared-mime-info

    caches-compilation:
        plugin: nil
        after: [libreoffice]
        install: |
            set -eux
            mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share
            cp -R $SNAPCRAFT_STAGE/usr/share/mime $SNAPCRAFT_PART_INSTALL/usr/share/
            cp -R $SNAPCRAFT_STAGE/usr/share/icons $SNAPCRAFT_PART_INSTALL/usr/share/
            cp -R $SNAPCRAFT_STAGE/usr/share/glib-2.0 $SNAPCRAFT_PART_INSTALL/usr/share/
            glib-compile-schemas $SNAPCRAFT_PART_INSTALL/usr/share/glib-2.0/schemas
            update-mime-database $SNAPCRAFT_PART_INSTALL/usr/share/mime
            for dir in $SNAPCRAFT_PART_INSTALL/usr/share/icons/*; do
                if [ -f "$dir/index.theme" ]; then
                    gtk-update-icon-cache --force "$dir"
                fi
            done
        prime:
            - usr/share/glib-2.0/schemas/*
            - usr/share/icons/*
            - usr/share/mime/*

apps:
    libreoffice:
        command: libreoffice.wrapper
        desktop: lib/libreoffice/share/xdg/startcenter.desktop
        plugs: &plugs
            - bluez
            - cups-control
            - desktop
            - gsettings
            - home
            - network
            - network-bind
            - opengl
            - removable-media
            - unity7
            - wayland
    base:
        command: libreoffice.wrapper --base
        desktop: lib/libreoffice/share/xdg/base.desktop
        plugs: *plugs
    calc:
        command: libreoffice.wrapper --calc
        desktop: lib/libreoffice/share/xdg/calc.desktop
        plugs: *plugs
    draw:
        command: libreoffice.wrapper --draw
        desktop: lib/libreoffice/share/xdg/draw.desktop
        plugs: *plugs
    impress:
        command: libreoffice.wrapper --impress
        desktop: lib/libreoffice/share/xdg/impress.desktop
        plugs: *plugs
    math:
        command: libreoffice.wrapper --math
        desktop: lib/libreoffice/share/xdg/math.desktop
        plugs: *plugs
    writer:
        command: libreoffice.wrapper --writer
        desktop: lib/libreoffice/share/xdg/writer.desktop
        plugs: *plugs
