name: build-test
on:
  pull_request:
  push:
    branches:
      - edge
      - stable

jobs:
  snap:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: free disk space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
    - uses: snapcore/action-build@v1
      id: snapcraft
    - uses: actions/upload-artifact@v2
      with:
        name: 'snap'
        path: ${{ steps.snapcraft.outputs.snap}}
